version: '3'
services:
  crowi:
    build: .
    command: npm run dev
    tty: true
    environment:
      DEBUG: "crowi:*"
      NODE_ENV: development
      MONGO_URI: mongodb://mongodb:27017/crowi
      REDIS_URL: redis://redis:6379/crowi
      ELASTICSEARCH_URI: elasticsearch1:9200/
      PLANTUML_URI: //localhost:8080
      FILE_UPLOAD: local
    volumes:
    - .:/crowi
    - node_modules:/crowi/node_modules
    - css:/crowi/public/css
    - js:/crowi/public/js
    restart: always
    ports:
    - 3000:3000
    links:
    - mongodb
    - elasticsearch1
    - redis
    - plantuml

  gulp:
    build: .
    command: npm run build watch
    volumes:
    - .:/crowi
    - node_modules:/crowi/node_modules
    - css:/crowi/public/css
    - js:/crowi/public/js

  mongodb:
    image: mongo:3.6.3
    volumes:
    - ./data/mongodb:/data/db
    restart: always
    ports:
    - 27017:27017

  elasticsearch1:
    build:
      context: ./elasticsearch
    container_name: elasticsearch1
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ./data/elasticsearch1:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  elasticsearch2:
    build:
      context: ./elasticsearch
    container_name: elasticsearch2
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      discovery.zen.ping.unicast.hosts: elasticsearch1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ./data/elasticsearch2:/usr/share/elasticsearch/data

  redis:
    image: redis:4.0.8
    restart: always
    ports:
    - 6379:6379

  plantuml:
    image: plantuml/plantuml-server:latest
    restart: always
    ports:
    - 8080:8080

volumes:
  node_modules:
  css:
  js: